name: Local Release

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Example ip host http://192.168.1.00:9393'
        required: true
        
      environment:
        type: environment
        description: Select the environment

jobs:
  generate-local-release:
    env:
      HOST: ${{ github.event.inputs.host }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Assemble
        run: bash ./gradlew app-nexaas-omni:assembleGenericDebug

      - name: Upload our APK
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Release artifact
          path: app-nexaas-omni/build/outputs/apk/generic/debug/*.apk

